# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d42305dd70b2eaf3b1fbf06030344feda42fbe5ae1ea25a758e090b167a82daba39d51eaeb65308726c374b66b8eb49e69b586cfdc8e4642ba254958fe5f3ca

test:
  secret_key_base: 3706b64004409e27793a0402aac05012aa3c3d3f446c3a0a921024d41ac6af0cdf46670c98c6901032b8ae009a904c6c1d705325e4efd70cf0635b8dcea43923

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
